create a system for reporting errors
se310-t6/politicry pull request #100
Opened 2022-10-04 23:37 UTC by k-yle

## Todo

- [x] change the "Report an issue" button to open politicry.com/report instead
- [x] pass data from the extension to politicry.com/report
- [x] create politicry.com/report
- [x] receive data on the report website from the extension
- [x] make the submit button send an email

## Motivation

See issue #99. We need a better system for reporting issues, just redirecting a user to github issues is not adequate. 

## Attached GitHub issue

Closes #99

## Checklist

### Documentation

- [x] ~~Updated the readme documents (`README.md` etc.)~~
- [x] New functions and methods have additional comments added to document their usage

### Local Build

- [x] Ran all pre-commit hooks `pre-commit run --all-files`
- [x] Extension has been tested to build correctly `cd extension && yarn && yarn build`
- [x] Backend has been tested to build correctly `cd backend && docker-compose build`
- [x] Extension test suite has been run locally `cd extension && yarn && yarn test`
- [x] Backend test suite has been run locally `cd backend && python3 -m unittest`

### GitHub

- [x] Target branch has been set correctly
- [x] PR has been rebased onto target branch
- [x] PR has been assigned an owner
- [x] Author has performed a self-review of the code
- [x] Removed the WIP message from the top of this PR

2022-10-04 23:39 UTC, k-yle commented on website/__tests__/report-issue.test.js
> +    expect(screen.getByDisplayValue("undefined GB")).toBeTruthy();
this looks weird, but it's because the virtual test environment doesn't have access to information like this. In a real browser it say "16 GB" etc.

2022-10-05 00:29 UTC, Destiny-02 requested changes
Are you able to update the PR description and include how you implemented some things e.g. how you retrieved the data from the extension and auto-filled the website fields.  

Also, should the Blocked Words field be empty when you first install the extension and click report (the default list of words doesn't show). 

Other than that it looks great! And nice tests!
![image](https://user-images.githubusercontent.com/78716153/193953353-30474867-8e25-4fbf-b241-83b501ed3f66.png)

2022-10-06 06:49 UTC, k-yle commented
> Also, should the Blocked Words field be empty when you first install the extension and click report (the default list of words doesn't show).

good thinking, I've changed it to `"Not configured"`. This might be useful to identify users who have never edited the blocked words list.

🦖

2022-10-06 08:54 UTC, Destiny-02 approved these changes

2022-10-06 09:08 UTC, merged