add support for facebook
se310-t6/politicry pull request #107
Opened 2022-10-07 07:16 UTC by Kanelmis

Add support for Facebook following the same logic as `twitter.js`.  In addition, for Facebook, we support checking posts' text and the image alt. 

## Todo
- [x] support blurring post 
- [x] support blurring image

## Motivation
See issue https://github.com/se310-t6/politicry/issues/51. The aim is to support multiple social media platforms

## Attached GitHub issue
Partially addresses https://github.com/se310-t6/politicry/issues/51.

## Checklist

### Documentation

- [ ] Updated the readme documents (`README.md` etc.)
- [x] New functions and methods have additional comments added to document their usage

### Local Build

- [x] Ran all pre-commit hooks `pre-commit run --all-files`
- [x] Extension has been tested to build correctly `cd extension && yarn && yarn build`
- [x] Backend has been tested to build correctly `cd backend && docker-compose build`
- [x] Extension test suite has been run locally `cd extension && yarn && yarn test`
- [x] Backend test suite has been run locally `cd backend && python3 -m unittest`

### GitHub

- [x] Target branch has been set correctly
- [ ] PR has been rebased onto target branch
- [ ] PR has been assigned an owner
- [x] Author has performed a self-review of the code
- [x] Removed the WIP message from the top of this PR

2022-10-13 11:16 UTC, Destiny-02 approved these changes, later dismissed
Nice work! Tested and works :)
![image](https://user-images.githubusercontent.com/78716153/195582603-d5271bc0-a3fb-4376-ae5d-394c6dde274a.png)

2022-10-13 23:02 UTC, k-yle requested changes
nice work! i've left a few minor suggestions

2022-10-13 23:02 UTC, k-yle commented on extension/public/worker-test.html
> +    <div lang="en">🔴 This tweet is about Pizza 🔴</div>
```suggestion
    <div lang="en">🔴 This post is about Pizza 🔴</div>
```

2022-10-13 23:02 UTC, k-yle commented on extension/public/worker-test.html
> +    <div lang="en">🟢 This tweet is about Sushi 🟢</div>
```suggestion
    <div lang="en">🟢 This post is about Sushi 🟢</div>
```

2022-10-13 23:02 UTC, k-yle commented on extension/public/worker/facebook.js
> +      // div with an attribute called lang="en". Politicry only supports English (for now)
```suggestion
      // div with an attribute called data-ad-preview="message"
```

2022-10-14 20:02 UTC, k-yle approved these changes
looks good

2022-10-16 01:36 UTC, merged